// vue.js/src/App.vue
<template>
  <div id="app">
    <wc-stock-price></wc-stock-price>
    <wc-stock-finder v-if="showStockFinder"></wc-stock-finder>
    <button @click="showStockFinder = true">Show Finder</button>

    <github-stats username="savepong"></github-stats>
    <github-streak-stats username="savepong"></github-streak-stats>
    <github-top-langs langs-count="5"></github-top-langs>
    <wakatime-stats username="savepong"></wakatime-stats>
  </div>
</template>

<script>
export default {
  name: "app",
  data() {
    return { showStockFinder: false };
  },
  components: {},
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react.js/src/App.js
import React, { Component } from "react";
import "./App.css";

class App extends Component {
  state = {
    showStockFinder: false,
  };
  render() {
    let stockFinder = null;
    if (this.state.showStockFinder) {
      stockFinder = <wc-stock-finder></wc-stock-finder>;
    }
    return (
      <div className="App">
        <wc-stock-price></wc-stock-price>
        {stockFinder}
        <button onClick={() => this.setState({ showStockFinder: true })}>
          Show Finder
        </button>

        <github-stats username="savepong" />
        <github-streak-stats username="savepong" />
        <github-top-langs langs-count="5" />
        <wakatime-stats username="savepong" />
      </div>
    );
  }
}

export default App;
