// react.js/src/App.js
import React, { Component } from "react";
import "./App.css";

class App extends Component {
  state = {
    showStockFinder: false,
  };
  render() {
    let stockFinder = null;
    if (this.state.showStockFinder) {
      stockFinder = <wc-stock-finder></wc-stock-finder>;
    }
    return (
      <div className="App">
        <wc-stock-price></wc-stock-price>
        {stockFinder}
        <button onClick={() => this.setState({ showStockFinder: true })}>
          Show Finder
        </button>
      </div>
    );
  }
}

export default App;

// angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "angular";
  showStockFinder = false;
}

<wc-stock-price></wc-stock-price>
<wc-stock-finder *ngIf="showStockFinder"></wc-stock-finder>
<button (click)="showStockFinder = true">Show Finder</button>
